# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Isaias Silva
#email: luiz.isaias95@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://isaiassilva.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: #jekyllrb
github_username:  ssisaias
author:
  name: "Isaias Silva"
  email: "luiz.isaias95@gmail.com"
  url: "http://isaiassilva.com"

# Build settings
baseurl: "" # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:year/:title
paginate: 8
paginate_path: /page:num/

#theme: emerald
gems:
  - jekyll-feed
  - jekyll-paginate


# Custom variables
version: "1.0.0"


# Options
custom_header: false
custom_nav_footer: false
reverse: true